name: simpleautomate
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  process_run: ^1.2.2+1
  ffi: ^2.1.4
  path: ^1.9.1
  webview_flutter: ^4.0.10
  webview_flutter_android: ^4.0.10
  webview_flutter_wkwebview: ^3.18.2
  flutter_inappwebview: ^6.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
