// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-wUq7TIl-vSsLBfY6g-KZtOpVduuVtg',
    appId: '1:82529936747:web:2f19437b5d81724146582e',
    messagingSenderId: '82529936747',
    projectId: 'simple-automate',
    authDomain: 'simple-automate.firebaseapp.com',
    storageBucket: 'simple-automate.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWBSRl7gBgPcxrepWkVk0HWIw_yFT6Q1c',
    appId: '1:82529936747:android:d2f5f117950ea44d46582e',
    messagingSenderId: '82529936747',
    projectId: 'simple-automate',
    storageBucket: 'simple-automate.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDden0n8k-5c3fmhTPWADSPjF4XIFK8Yfs',
    appId: '1:82529936747:ios:ab55381525b0c49b46582e',
    messagingSenderId: '82529936747',
    projectId: 'simple-automate',
    storageBucket: 'simple-automate.firebasestorage.app',
    iosBundleId: 'com.example.simpleautomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDden0n8k-5c3fmhTPWADSPjF4XIFK8Yfs',
    appId: '1:82529936747:ios:ab55381525b0c49b46582e',
    messagingSenderId: '82529936747',
    projectId: 'simple-automate',
    storageBucket: 'simple-automate.firebasestorage.app',
    iosBundleId: 'com.example.simpleautomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-wUq7TIl-vSsLBfY6g-KZtOpVduuVtg',
    appId: '1:82529936747:web:637a7d1c2849659346582e',
    messagingSenderId: '82529936747',
    projectId: 'simple-automate',
    authDomain: 'simple-automate.firebaseapp.com',
    storageBucket: 'simple-automate.firebasestorage.app',
  );
}
